import type { Lang } from '../../shared/types.ts';

const sr = {
  invoice: 'FAKTURA',
  invoiceNo: 'Broj',
  issueDate: 'Datum izdavanja',
  serviceDate: 'Datum prometa',
  dueDate: 'Rok plaćanja',
  place: 'Mesto izdavanja',
  seller: 'Izdavalac',
  buyer: 'Kupac',
  pib: 'PIB',
  mb: 'MB',
  activityCode: 'Šifra delatnosti',
  email: 'Email',
  phone: 'Telefon',
  contact: 'Kontakt',
  no: 'Rb.',
  description: 'Opis',
  quantity: 'Kol.',
  unit: 'Jed.',
  price: 'Cena',
  amount: 'Iznos',
  subtotal: 'Osnovica',
  vat: 'PDV',
  total: 'Ukupno za uplatu',
  paymentInfo: 'Instrukcije za plaćanje',
  bankAccount: 'Tekući račun',
  bank: 'Banka',
  reference: 'Poziv na broj',
  iban: 'IBAN',
  swift: 'SWIFT/BIC',
  notes: 'Napomena',
  page: 'Strana',
  of: 'od',
  report: 'IZVEŠTAJ O RADU',
  reportFor: 'Prilog uz fakturu',
  period: 'Period',
  client: 'Klijent',
  date: 'Datum',
  hours: 'Sati',
  totalHours: 'Ukupno sati',
  totalShort: 'Ukupno',
  totalAmount: 'Ukupan iznos',
  flat: 'paušal',
  maintenance: 'održavanje',
  rate: 'Satnica',
  issuedBy: 'Fakturu izdao',
  generated: 'Generisano',
  paid: 'PLAĆENO',
  cancelled: 'STORNIRANO',
};

const en: typeof sr = {
  invoice: 'INVOICE',
  invoiceNo: 'Number',
  issueDate: 'Issue date',
  serviceDate: 'Date of supply',
  dueDate: 'Due date',
  place: 'Place of issue',
  seller: 'From',
  buyer: 'Bill to',
  pib: 'Tax ID',
  mb: 'Reg. No.',
  activityCode: 'Activity code',
  email: 'Email',
  phone: 'Phone',
  contact: 'Contact',
  no: '#',
  description: 'Description',
  quantity: 'Qty',
  unit: 'Unit',
  price: 'Price',
  amount: 'Amount',
  subtotal: 'Subtotal',
  vat: 'VAT',
  total: 'Total due',
  paymentInfo: 'Payment details',
  bankAccount: 'Account',
  bank: 'Bank',
  reference: 'Reference',
  iban: 'IBAN',
  swift: 'SWIFT/BIC',
  notes: 'Notes',
  page: 'Page',
  of: 'of',
  report: 'WORK REPORT',
  reportFor: 'Attachment to invoice',
  period: 'Period',
  client: 'Client',
  date: 'Date',
  hours: 'Hours',
  totalHours: 'Total hours',
  totalShort: 'Total',
  totalAmount: 'Total amount',
  flat: 'flat fee',
  maintenance: 'maintenance',
  rate: 'Rate',
  issuedBy: 'Issued by',
  generated: 'Generated',
  paid: 'PAID',
  cancelled: 'CANCELLED',
};

export type Labels = typeof sr;
export const LABELS: Record<Lang, Labels> = { sr, en };
